### ISSUE TITLE
Problems in IE

### ISSUE THREAD

**Issue by ctpstudy** [uuchat/uuchat#1]
Follow the guide, it works.

I found problems in IE:
1. Pages don't display normal in IE8;
2. can't send pic in IE10.

**Comment by hoorace** [comment]
we had add socket.io.js which not compress for ie8, 
microsoft had not support ie8 recently, you need update you IE.

**Comment by ctpstudy** [comment]
Most IE compability problems are disappeared After updating code.
Still can't send pictures in IE9 , Is it forbidden by backend?

**Comment by hoorace** [comment]
for IE9 or low， we only let user send message，and now, we did not has time to compatible IE for more features.

**Comment by hoorace** [comment]
@ctpstudy if you have times , you can help us for IE compatible.
